// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GoogleCloudProvider) DeepCopyInto(out *GoogleCloudProvider) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GoogleCloudProvider.
func (in *GoogleCloudProvider) DeepCopy() *GoogleCloudProvider {
	if in == nil {
		return nil
	}
	out := new(GoogleCloudProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KMSProvider) DeepCopyInto(out *KMSProvider) {
	*out = *in
	if in.GoogleCloud != nil {
		in, out := &in.GoogleCloud, &out.GoogleCloud
		*out = new(GoogleCloudProvider)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KMSProvider.
func (in *KMSProvider) DeepCopy() *KMSProvider {
	if in == nil {
		return nil
	}
	out := new(KMSProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKMS) DeepCopyInto(out *SecretKMS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKMS.
func (in *SecretKMS) DeepCopy() *SecretKMS {
	if in == nil {
		return nil
	}
	out := new(SecretKMS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretKMS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKMSList) DeepCopyInto(out *SecretKMSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretKMS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKMSList.
func (in *SecretKMSList) DeepCopy() *SecretKMSList {
	if in == nil {
		return nil
	}
	out := new(SecretKMSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecretKMSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKMSSpec) DeepCopyInto(out *SecretKMSSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKMSSpec.
func (in *SecretKMSSpec) DeepCopy() *SecretKMSSpec {
	if in == nil {
		return nil
	}
	out := new(SecretKMSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKMSStatus) DeepCopyInto(out *SecretKMSStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKMSStatus.
func (in *SecretKMSStatus) DeepCopy() *SecretKMSStatus {
	if in == nil {
		return nil
	}
	out := new(SecretKMSStatus)
	in.DeepCopyInto(out)
	return out
}
