apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretkmses.kubaj.kms
spec:
  group: kubaj.kms
  names:
    kind: SecretKMS
    listKind: SecretKMSList
    plural: secretkmses
    singular: secretkms
  scope: Namespaced
  version: v1alpha1
