apiVersion: v1
kind: ServiceAccount
metadata:
  name: kms-operator

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: secretkmses.kubaj.kms
spec:
  group: kubaj.kms
  names:
    kind: SecretKMS
    listKind: SecretKMSList
    plural: secretkmses
    singular: secretkms
  scope: Namespaced
  version: v1alpha1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kms-operator
  template:
    metadata:
      labels:
        name: kms-operator
    spec:
      serviceAccountName: kms-operator
      containers:
      - name: kms-operator
        image: gcr.io/kubaj-public/kms-operator:0.1.1
        ports:
        - containerPort: 60000
          name: metrics
        args: ["-google-provider", "-google-service-account", "/etc/google/credentials.json"]
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: OPERATOR_NAME
          value: "kms-operator"
        volumeMounts:
        - name: google-sa-kms
          mountPath: "/etc/google"
          readOnly: true
      volumes:
      - name: google-sa-kms
        secret:
          secretName: google-sa-kms

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kms-operator
rules:
- apiGroups:
  - kubaj.kms
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - "*"

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kms-operator
subjects:
- kind: ServiceAccount
  name: kms-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kms-operator
  apiGroup: rbac.authorization.k8s.io
